baseURL = "/"
languageCode = "en-us"
theme = "terminal"
copyright = "© 2025 Paul Hübner"
pagination.pagerSize = 5

[markup.highlight]
  noClasses = false

[params]
  showMenuItems = 5
  fullWidthTheme = false
  centerTheme = true
  autoCover = true
  showLastUpdated = false
  readingTime = true
  # dateFormat = "2006-01-02 3:04:06 PM MST"

[languages]
  [languages.en]
    languageName = "English"
    title = "Paul Hübner"

    [languages.en.params]
      subtitle = "My personal blog"
      owner = "Paul Hübner"
      keywords = "computer science, programming, technology"
      copyright = "Paul Hübner"
      menuMore = "Show more"
      readMore = "Read more"
      readOtherPosts = "Read other posts"
      newerPosts = "Newer posts"
      olderPosts = "Older posts"
      missingContentMessage = "Page not found!"
      missingBackButtonLabel = "Take me back to the home page"
      minuteReadingTime = "min read"
      words = "words"

      [languages.en.params.logo]
        logoText = "Paul Hübner"
        logoHomeLink = "/"

      [languages.en.menu]
        [[languages.en.menu.main]]
          identifier = "home"
          name = "Home"
          url = "/"
          weight = 1

        [[languages.en.menu.main]]
          identifier = "about"
          name = "About"
          url = "/about"
          weight = 2

        [[languages.en.menu.main]]
          identifier = "blog"
          name = "Blog"
          url = "/post"
          weight = 3

        [[languages.en.menu.main]]
          identifier = "publications"
          name = "Publications"
          url = "/publications"
          weight = 4

